# Generated by Django 5.0.1 on 2024-02-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='age',
        ),
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(default='Unknown', max_length=6),
        ),
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='students',
            name='phone_No',
            field=models.IntegerField(default=100),
        ),
    ]
