# Generated by Django 5.0.1 on 2024-02-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0002_remove_students_age_students_gender_students_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='address',
            new_name='student_address',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='gender',
            new_name='student_gender',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='gmail',
            new_name='student_gmail',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='image',
            new_name='student_image',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='phone_No',
            new_name='student_phone_No',
        ),
    ]
